"""
ResolveIQ - Resolution Ranking Learning

Converts human review / historical resolution feedback into
ranking-training examples and trains a LambdaMART resolution ranker.

Learning flow:

    ResolutionPipeline
          |
          v
    Retrieved candidates
          |
          v
      Human review
       /       \
   approved   rejected
       |
       v
  Ranking examples
       |
       v
  Quality filtering
       |
       v
    LambdaMART
       |
       v
resolution_ranker.txt

The current ResolveIQ bootstrap dataset uses the candidate-list schema:

{
    "query": "...",
    "resolution": "...",
    "candidates": [
        {
            "document_id": "...",
            "label": 1,
            "query_similarity": ...,
            "resolution_similarity": ...,
            "combined_similarity": ...,
            "category_match": ...,
            "source_match": ...,
            "authority_score": ...,
            "historical_supervision_weight": ...,
            "approval_signal": ...,
            "success_signal": ...,
            "edit_penalty": ...,
            "candidate_quality": ...
        }
    ],
    "supervision": {
        "weight": ...
    }
}

The learner also retains backward compatibility with the older
positive_features / negative_features schema.

Important design principles:

1. Never treat every retrieved document as equally useful.
2. Approved evidence becomes positive evidence.
3. Retrieved-but-unused evidence becomes hard negatives.
4. Rejected resolutions do NOT automatically make every retrieved
   document negative.
5. Agent edits reduce confidence in the original ranking.
6. Low-quality / ambiguous feedback is excluded from training.
7. Ranking groups contain all candidates for a query.
8. Resolution-aware features are learned directly by LambdaMART.
"""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np


# ============================================================
# Configuration
# ============================================================

ARTIFACT_DIR = Path("artifacts")

EXAMPLES_PATH = ARTIFACT_DIR / "ranking_examples.jsonl"
TRAINING_PATH = ARTIFACT_DIR / "ranking_training.jsonl"

MODEL_PATH = ARTIFACT_DIR / "resolution_ranker.txt"
FEATURES_PATH = ARTIFACT_DIR / "resolution_ranker_features.json"

MIN_TRAINING_EXAMPLES = 20


# ============================================================
# Feature schema
# ============================================================
#
# These features are generated by the current ResolveIQ
# bootstrap_ranking_examples pipeline.
#
# The learner consumes them directly instead of trying to
# reconstruct the features from incomplete metadata.
# ============================================================

FEATURE_NAMES = [
    "query_similarity",
    "resolution_similarity",
    "combined_similarity",
    "category_match",
    "source_match",
    "authority_score",
    "historical_supervision_weight",
    "approval_signal",
    "success_signal",
    "edit_penalty",
    "candidate_quality",
]


# ============================================================
# Data structures
# ============================================================

@dataclass
class RankingExample:
    example_id: str

    query: str
    context: dict[str, Any]

    positive_id: str
    negative_id: str

    positive_features: dict[str, float]
    negative_features: dict[str, float]

    label: int
    weight: float

    feedback_decision: str
    rating: int | None

    edited: bool
    edit_distance: float

    reason: str | None

    created_at: str


# ============================================================
# Utility functions
# ============================================================

def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def clamp(
    value: float,
    low: float = 0.0,
    high: float = 1.0,
) -> float:
    return max(low, min(high, float(value)))


def normalize_text(text: str) -> str:
    return " ".join(
        str(text or "")
        .lower()
        .strip()
        .split()
    )


def stable_id(*values: Any) -> str:
    payload = "||".join(
        normalize_text(str(value))
        for value in values
    )

    return hashlib.sha256(
        payload.encode("utf-8")
    ).hexdigest()[:20]


def safe_float(
    value: Any,
    default: float = 0.0,
) -> float:
    try:
        value = float(value)

        if not math.isfinite(value):
            return default

        return value

    except (TypeError, ValueError):
        return default


# ============================================================
# Edit measurement
# ============================================================

def normalized_edit_distance(
    original: str,
    edited: str,
) -> float:
    """
    Approximate normalized Levenshtein distance.

    0.0 = no edit
    1.0 = very large edit

    Uses difflib rather than an additional dependency.
    """

    import difflib

    original = normalize_text(original)
    edited = normalize_text(edited)

    if original == edited:
        return 0.0

    if not original or not edited:
        return 1.0

    similarity = difflib.SequenceMatcher(
        None,
        original,
        edited,
    ).ratio()

    return clamp(1.0 - similarity)


# ============================================================
# Feedback quality
# ============================================================

def feedback_quality(
    decision: str,
    rating: int | None,
    edited: bool,
    edit_distance: float,
) -> float:
    """
    Calculate confidence in human feedback.

    Strong approval:
        approved + 5 + no edit -> 1.0

    Weak approval:
        approved + 3 + heavy edit -> lower weight

    Rejection:
        useful as negative feedback, but deliberately weighted
        lower than strong approval because rejection can happen
        for reasons unrelated to retrieval.
    """

    decision = normalize_text(decision)

    rating_value = (
        clamp(rating / 5.0)
        if rating is not None
        else 0.6
    )

    if decision == "approved":

        quality = 0.65 + 0.35 * rating_value

        if edited:
            quality *= max(
                0.25,
                1.0 - 0.70 * edit_distance,
            )

        return clamp(quality)

    if decision == "rejected":

        quality = 0.55

        if rating is not None:
            quality *= (
                0.7
                + 0.3 * (1.0 - rating_value)
            )

        return clamp(quality)

    return 0.0


# ============================================================
# Candidate feature extraction
# ============================================================

def extract_features(
    query: str,
    candidate: dict[str, Any],
) -> dict[str, float]:
    """
    Legacy candidate feature extraction.

    Kept for compatibility with the original ResolveIQ
    human-feedback pipeline.
    """

    metadata = candidate.get(
        "metadata",
        {},
    ) or {}

    content = str(
        candidate.get(
            "content",
            "",
        )
    )

    retrieval_score = safe_float(
        candidate.get("score", 0.0)
    )

    context_match = safe_float(
        metadata.get(
            "context_match",
            0.5,
        ),
        0.5,
    )

    authority = safe_float(
        metadata.get(
            "authority",
            0.5,
        ),
        0.5,
    )

    freshness = safe_float(
        metadata.get(
            "freshness",
            0.5,
        ),
        0.5,
    )

    historical_success = safe_float(
        metadata.get(
            "historical_success",
            0.5,
        ),
        0.5,
    )

    resolution_frequency = safe_float(
        metadata.get(
            "resolution_frequency",
            0.0,
        )
    )

    source_quality = safe_float(
        metadata.get(
            "source_quality",
            authority,
        ),
        authority,
    )

    query_tokens = set(
        normalize_text(query).split()
    )

    candidate_tokens = set(
        normalize_text(content).split()
    )

    if query_tokens and candidate_tokens:

        overlap = (
            len(query_tokens & candidate_tokens)
            / max(len(query_tokens), 1)
        )

    else:
        overlap = 0.0

    return {
        "retrieval_score": clamp(
            retrieval_score
        ),
        "context_match": clamp(
            context_match
        ),
        "authority": clamp(
            authority
        ),
        "freshness": clamp(
            freshness
        ),
        "historical_success": clamp(
            historical_success
        ),
        "resolution_frequency": clamp(
            resolution_frequency
        ),
        "source_quality": clamp(
            source_quality
        ),
        "query_length": clamp(
            len(query) / 500.0
        ),
        "candidate_length": clamp(
            len(content) / 5000.0
        ),
        "query_candidate_similarity": clamp(
            overlap
        ),
    }


# ============================================================
# Current ResolveIQ bootstrap feature extraction
# ============================================================

def extract_bootstrap_features(
    candidate: dict[str, Any],
) -> dict[str, float]:
    """
    Convert a current ResolveIQ bootstrap candidate into
    the canonical LambdaMART feature vector.

    The bootstrap generator already computes these
    resolution-aware features, so the learner consumes
    them directly.
    """

    return {
        "query_similarity": safe_float(
            candidate.get(
                "query_similarity",
                0.0,
            )
        ),

        "resolution_similarity": safe_float(
            candidate.get(
                "resolution_similarity",
                0.0,
            )
        ),

        "combined_similarity": safe_float(
            candidate.get(
                "combined_similarity",
                0.0,
            )
        ),

        "category_match": safe_float(
            candidate.get(
                "category_match",
                0.0,
            )
        ),

        "source_match": safe_float(
            candidate.get(
                "source_match",
                0.0,
            )
        ),

        "authority_score": safe_float(
            candidate.get(
                "authority_score",
                0.0,
            )
        ),

        "historical_supervision_weight": safe_float(
            candidate.get(
                "historical_supervision_weight",
                0.0,
            )
        ),

        "approval_signal": safe_float(
            candidate.get(
                "approval_signal",
                0.0,
            )
        ),

        "success_signal": safe_float(
            candidate.get(
                "success_signal",
                0.0,
            )
        ),

        "edit_penalty": safe_float(
            candidate.get(
                "edit_penalty",
                0.0,
            )
        ),

        "candidate_quality": safe_float(
            candidate.get(
                "candidate_quality",
                0.0,
            )
        ),
    }


# ============================================================
# Candidate lookup
# ============================================================

def candidate_map(
    candidates: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    return {
        str(candidate["id"]): candidate
        for candidate in candidates
        if candidate.get("id")
    }


# ============================================================
# Pairwise example generation
# ============================================================

def generate_pairwise_examples(
    *,
    query: str,
    context: dict[str, Any],
    retrieved_evidence: list[dict[str, Any]],
    selected_evidence_ids: list[str],
    decision: str,
    rating: int | None = None,
    reason: str | None = None,
    original_response: str = "",
    edited_response: str = "",
) -> list[RankingExample]:

    decision = normalize_text(decision)

    candidates = candidate_map(
        retrieved_evidence
    )

    selected = {
        str(x)
        for x in selected_evidence_ids
    }

    if decision not in {
        "approved",
        "rejected",
    }:
        return []

    edited = bool(
        normalize_text(edited_response)
        and normalize_text(original_response)
        and normalize_text(edited_response)
        != normalize_text(original_response)
    )

    edit_distance = (
        normalized_edit_distance(
            original_response,
            edited_response,
        )
        if edited
        else 0.0
    )

    weight = feedback_quality(
        decision,
        rating,
        edited,
        edit_distance,
    )

    if weight < 0.30:
        return []

    # --------------------------------------------------------
    # APPROVED
    #
    # Selected evidence = positive.
    # Other retrieved evidence = hard negative.
    # --------------------------------------------------------

    if decision == "approved":

        positives = [
            candidates[evidence_id]
            for evidence_id in selected
            if evidence_id in candidates
        ]

        negatives = [
            candidate
            for candidate_id, candidate in candidates.items()
            if candidate_id not in selected
        ]

        if not positives or not negatives:
            return []

    # --------------------------------------------------------
    # REJECTED
    #
    # We do NOT automatically assume every candidate is bad.
    # --------------------------------------------------------

    else:

        if not candidates:
            return []

        ordered = sorted(
            candidates.values(),
            key=lambda x: safe_float(
                x.get("score", 0.0)
            ),
            reverse=True,
        )

        negatives = ordered[:1]

        positives = ordered[1:]

        if not positives or not negatives:
            return []

    examples = []

    negatives = sorted(
        negatives,
        key=lambda x: safe_float(
            x.get("score", 0.0)
        ),
        reverse=True,
    )[:5]

    positives = positives[:3]

    for positive in positives:

        positive_features = extract_features(
            query,
            positive,
        )

        for negative in negatives:

            negative_features = extract_features(
                query,
                negative,
            )

            example_id = stable_id(
                query,
                positive["id"],
                negative["id"],
            )

            examples.append(
                RankingExample(
                    example_id=example_id,

                    query=query,
                    context=context,

                    positive_id=str(
                        positive["id"]
                    ),

                    negative_id=str(
                        negative["id"]
                    ),

                    positive_features=positive_features,
                    negative_features=negative_features,

                    label=1,
                    weight=weight,

                    feedback_decision=decision,
                    rating=rating,

                    edited=edited,
                    edit_distance=edit_distance,

                    reason=reason,

                    created_at=utc_now(),
                )
            )

    return examples


# ============================================================
# Persistence
# ============================================================

def load_existing_ids(
    path: Path = EXAMPLES_PATH,
) -> set[str]:

    if not path.exists():
        return set()

    ids = set()

    with path.open(
        "r",
        encoding="utf-8",
    ) as f:

        for line in f:

            if not line.strip():
                continue

            try:
                row = json.loads(line)

                if row.get("example_id"):
                    ids.add(
                        row["example_id"]
                    )

            except json.JSONDecodeError:
                continue

    return ids


def append_ranking_examples(
    examples: list[RankingExample],
    path: Path = EXAMPLES_PATH,
) -> int:

    if not examples:
        return 0

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    existing_ids = load_existing_ids(
        path
    )

    written = 0

    with path.open(
        "a",
        encoding="utf-8",
    ) as f:

        for example in examples:

            if example.example_id in existing_ids:
                continue

            f.write(
                json.dumps(
                    asdict(example),
                    ensure_ascii=False,
                )
                + "\n"
            )

            existing_ids.add(
                example.example_id
            )

            written += 1

    return written


# ============================================================
# Convert ranking examples → LightGBM rows
# ============================================================

def build_training_rows(
    examples_path: Path = EXAMPLES_PATH,
):
    """
    Convert ResolveIQ ranking examples into LambdaMART rows.

    Current schema:

        example
          └── candidates[]
                ├── label = 1
                └── label = 0

    Every query becomes one LightGBM ranking group.

    Backward compatibility:

    Older examples containing:

        positive_features
        negative_features

    are also supported.
    """

    rows = []
    groups = []

    if not examples_path.exists():
        return rows, groups

    with examples_path.open(
        "r",
        encoding="utf-8",
    ) as f:

        for line_number, line in enumerate(
            f,
            start=1,
        ):

            if not line.strip():
                continue

            try:
                example = json.loads(line)

            except json.JSONDecodeError as exc:
                print(
                    f"Skipping invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            query = str(
                example.get(
                    "query",
                    "",
                )
            ).strip()

            if not query:
                continue

            # ====================================================
            # CURRENT BOOTSTRAP SCHEMA
            # ====================================================

            candidates = example.get(
                "candidates"
            )

            if isinstance(
                candidates,
                list,
            ):

                query_rows = []

                supervision = (
                    example.get(
                        "supervision",
                        {},
                    )
                    or {}
                )

                example_weight = safe_float(
                    example.get(
                        "weight",
                        supervision.get(
                            "weight",
                            1.0,
                        ),
                    ),
                    1.0,
                )

                for candidate in candidates:

                    if not isinstance(
                        candidate,
                        dict,
                    ):
                        continue

                    document_id = str(
                        candidate.get(
                            "document_id",
                            candidate.get(
                                "id",
                                "",
                            ),
                        )
                    )

                    if not document_id:
                        continue

                    label = int(
                        candidate.get(
                            "label",
                            0,
                        )
                    )

                    features = extract_bootstrap_features(
                        candidate
                    )

                    query_rows.append(
                        {
                            "query_id": stable_id(
                                query
                            ),

                            "document_id": document_id,

                            "features": features,

                            "label": 1 if label > 0 else 0,

                            "weight": max(
                                0.0,
                                example_weight,
                            ),
                        }
                    )

                positive_count = sum(
                    1
                    for row in query_rows
                    if row["label"] == 1
                )

                negative_count = sum(
                    1
                    for row in query_rows
                    if row["label"] == 0
                )

                # LambdaMART needs ranking information.
                # A query with only positives or only negatives
                # provides no useful ordering signal.
                if (
                    positive_count == 0
                    or negative_count == 0
                ):
                    continue

                rows.extend(
                    query_rows
                )

                # Entire candidate list = one ranking group.
                groups.append(
                    len(query_rows)
                )

                continue

            # ====================================================
            # LEGACY PAIRWISE SCHEMA
            # ====================================================

            if (
                "positive_features" in example
                and "negative_features" in example
            ):

                positive = example[
                    "positive_features"
                ]

                negative = example[
                    "negative_features"
                ]

                pair_rows = [
                    {
                        "query_id": stable_id(
                            query
                        ),

                        "document_id": str(
                            example.get(
                                "positive_id",
                                "",
                            )
                        ),

                        "features": positive,

                        "label": 1,

                        "weight": safe_float(
                            example.get(
                                "weight",
                                1.0,
                            ),
                            1.0,
                        ),
                    },

                    {
                        "query_id": stable_id(
                            query
                        ),

                        "document_id": str(
                            example.get(
                                "negative_id",
                                "",
                            )
                        ),

                        "features": negative,

                        "label": 0,

                        "weight": safe_float(
                            example.get(
                                "weight",
                                1.0,
                            ),
                            1.0,
                        ),
                    },
                ]

                rows.extend(
                    pair_rows
                )

                groups.append(
                    len(pair_rows)
                )

    return rows, groups


# ============================================================
# Train LambdaMART
# ============================================================

def train_ranker(
    examples_path: Path = EXAMPLES_PATH,
):

    try:
        from lightgbm import LGBMRanker

    except ImportError as exc:

        raise RuntimeError(
            "LightGBM is not installed. "
            "Run: pip install lightgbm"
        ) from exc

    rows, groups = build_training_rows(
        examples_path
    )

    if not rows:

        raise RuntimeError(
            "No ranking examples available."
        )

    if len(rows) < MIN_TRAINING_EXAMPLES:

        raise RuntimeError(
            f"Only {len(rows)} training rows "
            f"available. Need at least "
            f"{MIN_TRAINING_EXAMPLES}."
        )

    # ========================================================
    # Feature matrix
    # ========================================================

    X = np.asarray(
        [
            [
                safe_float(
                    row["features"].get(
                        feature,
                        0.0,
                    )
                )

                for feature in FEATURE_NAMES
            ]

            for row in rows
        ],
        dtype=np.float32,
    )

    y = np.asarray(
        [
            row["label"]
            for row in rows
        ],
        dtype=np.float32,
    )

    sample_weights = np.asarray(
        [
            row["weight"]
            for row in rows
        ],
        dtype=np.float32,
    )

    # ========================================================
    # LambdaMART
    #
    # Small dataset → intentionally conservative model.
    # ========================================================

    model = LGBMRanker(
        objective="lambdarank",

        metric="ndcg",

        n_estimators=80,
        learning_rate=0.04,

        num_leaves=7,
        max_depth=4,

        min_child_samples=5,

        subsample=0.9,
        colsample_bytree=0.9,

        reg_alpha=0.5,
        reg_lambda=1.0,

        random_state=42,

        verbosity=-1,
    )

    # ========================================================
    # Train
    # ========================================================

    model.fit(
        X,
        y,

        group=groups,

        sample_weight=sample_weights,
    )

    # ========================================================
    # Save artifacts
    # ========================================================

    ARTIFACT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    model.booster_.save_model(
        str(MODEL_PATH)
    )

    FEATURES_PATH.write_text(
        json.dumps(
            {
                "features": FEATURE_NAMES,

                "training_rows": len(rows),

                "queries": len(groups),

                "created_at": utc_now(),

                "model_type": (
                    "LightGBM LambdaMART"
                ),

                "objective": (
                    "resolution-aware ranking"
                ),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    # ========================================================
    # Save flattened training representation
    # ========================================================

    with TRAINING_PATH.open(
        "w",
        encoding="utf-8",
    ) as f:

        for row in rows:

            f.write(
                json.dumps(
                    row,
                    ensure_ascii=False,
                )
                + "\n"
            )

    # ========================================================
    # Feature importance
    # ========================================================

    try:

        importance = model.booster_.feature_importance(
            importance_type="gain"
        )

        feature_importance = {
            feature: float(score)
            for feature, score in zip(
                FEATURE_NAMES,
                importance,
            )
        }

    except Exception:
        feature_importance = {}

    return {
        "training_rows": len(rows),

        "queries": len(groups),

        "model": str(
            MODEL_PATH
        ),

        "features": FEATURE_NAMES,

        "feature_importance": feature_importance,
    }


# ============================================================
# CLI
# ============================================================

if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Train the ResolveIQ "
            "resolution-aware LambdaMART ranker."
        )
    )

    parser.add_argument(
        "--train",
        action="store_true",
        help=(
            "Train LambdaMART from "
            "stored ranking examples."
        ),
    )

    args = parser.parse_args()

    if args.train:

        result = train_ranker()

        print(
            json.dumps(
                result,
                indent=2,
            )
        )

    else:

        print(
            "ResolveIQ ranking-learning module loaded."
        )

        print(
            f"Examples: {EXAMPLES_PATH}"
        )

        print(
            "Use --train to train LambdaMART."
        )